[package]
name = "texture_packer"
version = "0.1.0"
authors = ["Coeuvre <coeuvre@gmail.com>"]
keywords = ["texture", "packer", "sprite", "packing", "rectangle"]
description = "A rectangle packing library using the skyline heuristic"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/texture_packer.git"
homepage = "https://github.com/PistonDevelopers/texture_packer"
documentation = "http://docs.piston.rs/texture_packer"

[lib]
name = "texture_packer"

[dev-dependencies]
rand = "0.3.14"
image = "0.10.1"